namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service
  tag: 1ce24d229150a529ccbccbd7d506de0e7e99eb81
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8005
  targetPort: 8005

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

readinessProbe:
  enabled: true
  path: /health
  port: 8005
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8005
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8005"

configMapData:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/762103020993/togglemaster-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"

configMap:
  enabled: true
  name: analytics-service-config

serviceAccount:
  create: true
  name: analytics-service
