namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service
  tag: 7b18d105f6bcb563e5ca06f8c56f312979863f63
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8003
  targetPort: 8003

autoscaling:
  enabled: false

readinessProbe:
  enabled: true
  path: /health
  port: 8003
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8003
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8003"

configMapData:
  AUTH_SERVICE_URL: "http://auth-service:8001"

configMap:
  enabled: true
  name: targeting-service-config

externalSecret:
  enabled: true
  name: targeting-service-rds
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/rds/targeting
        property: connection_string

serviceAccount:
  create: true
  name: targeting-service

ingress:
  enabled: true
  groupOrder: "30"
  paths:
    - path: /rules

migration:
  enabled: true
  sql: |
    CREATE TABLE IF NOT EXISTS targeting_rules (
        id SERIAL PRIMARY KEY,
        flag_name VARCHAR(100) UNIQUE NOT NULL,
        is_enabled BOOLEAN NOT NULL DEFAULT true,
        rules JSONB NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE OR REPLACE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    
    DROP TRIGGER IF EXISTS set_timestamp ON targeting_rules;
    
    CREATE TRIGGER set_timestamp
    BEFORE UPDATE ON targeting_rules
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_set_timestamp();
