namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service
  tag: 5f7bbcca01dc9c3bee80366f5a0202e867789665
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8003
  targetPort: 8003

autoscaling:
  enabled: false

readinessProbe:
  enabled: true
  path: /health
  port: 8003
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8003
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8003"

configMapData:
  AUTH_SERVICE_URL: "http://auth-service:8001"

configMap:
  enabled: true
  name: targeting-service-config

externalSecret:
  enabled: true
  name: targeting-service-rds
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/rds/targeting
        property: connection_string

serviceAccount:
  create: true
  name: targeting-service

ingress:
  enabled: true
  groupOrder: "30"
  paths:
    - path: /rules
