replicaCount: 2

image:
  repository: "123456789012.dkr.ecr.us-east-1.amazonaws.com/togglemaster"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

readinessProbe:
  enabled: true
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8080
  initialDelaySeconds: 20
  periodSeconds: 20

env: []
configMapData: {}
configMap:
  enabled: false
  name: ""
secret:
  enabled: false
  name: ""
externalSecret:
  enabled: false
  name: ""
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  data: []
serviceAccount:
  create: true
  name: ""
  annotations: {}

ingress:
  enabled: false
  className: alb
  groupName: togglemaster
  groupOrder: ""
  scheme: internet-facing
  targetType: ip
  listenPorts: '[{"HTTP":80}]'
  healthcheckPath: ""
  host: ""
  annotations: {}
  paths: []

migration:
  enabled: false
  image: postgres:16-alpine
  databaseUrlKey: DATABASE_URL
  backoffLimit: 3
  seedApiKeys: []
  sql: ""

keda:
  enabled: false
  minReplicaCount: 0
  maxReplicaCount: 15
  pollingInterval: 20
  cooldownPeriod: 60
  queueURL: ""
  queueLength: "500"
  awsRegion: us-east-1
  identityOwner: operator

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
