namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/flag-service
  tag: c77af4ec17301f19531872731acd3dfd1b781729
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8002
  targetPort: 8002

autoscaling:
  enabled: false

readinessProbe:
  enabled: true
  path: /health
  port: 8002
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8002
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8002"

configMapData:
  AUTH_SERVICE_URL: "http://auth-service:8001"

configMap:
  enabled: true
  name: flag-service-config

secret:
  enabled: true
  name: flag-service-rds-secret

serviceAccount:
  create: true
  name: flag-service
