namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/flag-service
  tag: be198eb853e5add8d2b1c527cad045f1cfd4760b
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8002
  targetPort: 8002

autoscaling:
  enabled: false

readinessProbe:
  enabled: true
  path: /health
  port: 8002
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8002
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8002"

configMapData:
  AUTH_SERVICE_URL: "http://auth-service:8001"

configMap:
  enabled: true
  name: flag-service-config

externalSecret:
  enabled: true
  name: flag-service-rds
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/rds/flags
        property: connection_string

serviceAccount:
  create: true
  name: flag-service
