namespace: togglemaster
replicaCount: 2

image:
  repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service
  tag: b1ca230de01574e1b7bd42dc427bfaae517033a1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 8004
  targetPort: 8004

autoscaling:
  enabled: false

readinessProbe:
  enabled: true
  path: /health
  port: 8004
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  port: 8004
  initialDelaySeconds: 20
  periodSeconds: 20

env:
  - name: APP_ENV
    value: prod
  - name: PORT
    value: "8004"

configMapData:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/762103020993/togglemaster-evaluation-events"
  REDIS_URL: "set-by-deploy-from-ssm"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"

configMap:
  enabled: true
  name: evaluation-service-config

externalSecret:
  enabled: true
  name: evaluation-service-app
  data:
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: togglemaster/app/evaluation
        property: SERVICE_API_KEY

serviceAccount:
  create: true
  name: evaluation-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::762103020993:role/role-eks-togglemaster-apps

ingress:
  enabled: true
  groupOrder: "40"
  paths:
    - path: /evaluate
